---
driver:
  name: docker
  hostname: ceph.ci.local
  use_sudo: false

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  require_chef: false
  log_level: error
  formula: ceph
  grains:
    noservices: True
  vendor_repo:
    - type: apt
      url: http://download.ceph.com/debian-jewel
      key_url: https://download.ceph.com/keys/release.asc
      components: main
      distribution: xenial
  state_top:
    base:
      "*":
        - ceph
  pillars:
    top.sls:
      base:
        "*":
          - ceph

verifier:
  name: inspec
  sudo: true


platforms:
  - name: <%=ENV['PLATFORM'] ||  'saltstack-ubuntu-xenial-salt-stable' %>
    driver_config:
      image: <%=ENV['PLATFORM'] || 'epcim/salt-formulas:saltstack-ubuntu-xenial-salt-stable'%>
      platform: ubuntu

suites:

  - name: ceph_client_single
    provisioner:
      pillars-from-files:
        ceph.sls: tests/pillar/ceph_client_single.sls
  - name: ceph_mon_single
    provisioner:
      pillars-from-files:
        ceph.sls: tests/pillar/ceph_mon_single.sls
  - name: ceph_osd_single
    provisioner:
      pillars-from-files:
        ceph.sls: tests/pillar/ceph_osd_single.sls

# vim: ft=yaml sw=2 ts=2 sts=2 tw=125
